# Generated by Django 4.1.7 on 2023-03-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_customuser_alter_adminstrators_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(default='', max_length=40),
        ),
    ]
